# Stage 1
FROM node:22-alpine as builder

RUN corepack enable
RUN corepack prepare yarn

COPY . /build
WORKDIR /build

RUN yarn install --frozen-lockfile
RUN yarn build:staging

# Stage 2
FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /build/.output ./.output

ARG PORT=8002
ARG HOST=0.0.0.0

EXPOSE $PORT
ENV PORT=$PORT
ENV HOST=$HOST

ENTRYPOINT ["node", ".output/server/index.mjs"]